### ISSUE TITLE
Allow specifying domains skipping authentication

### ISSUE THREAD

**Issue by sbienkow-ninja** [onXmaps/cypress-iap#40]
We have a different local domain (other than `localhost`) used for locally-running UI.
It'd be nice if we could specify which domains should skip injecting the Authorization header.

I sadly don't know cypress yet to be able to contribute this myself (yet).

**Comment by coltdorsey** [comment]
What do you use to serve your app locally?

**Comment by sbienkow-ninja** [comment]
@coltdorsey We deploy the subset of our apps on local k8s cluster, in which the Ingress is always bound to the same static, local IP, which is returned by our DNS server (i.e. `local.example.com` returns `192.168.50.50`).

We will also have some "test" environments that are exposed without IAP (which we currently use only to protect the dev version of our application).

**Comment by vicwomg** [comment]
Not sure if this would solve your problem specifically, but I made a slight override to cypress-iap's cy.visit to skip IAP if the client_id returns null. This means domains behind IAP will use it, but if no IAP is detected it will skip it.

```
// cy.visit will be overridden to include IAP authentication
// place this in your support/e2e.ts

Cypress.Commands.overwrite("visit", (originalFn, subject, ...args) => {
  if (Cypress.config().baseUrl.indexOf("localhost") != -1) {
    return originalFn(subject, ...args);
  } else {
    cy.exec(`curl -I ${Cypress.config().baseUrl} | awk '/^location/ {split($NF, a, /[=&]/); print a[2]}'`)
      .then(client_id => {
        return client_id.stdout;
      })
      .then(client_id => {
        if (!!client_id) {
          cy.task("getIAPToken", {
            url: Cypress.config().baseUrl,
            cid: client_id,
          }).then(iapToken => {
            cy.intercept(`${Cypress.config().baseUrl}/**`, req => {
              req.headers["Proxy-Authorization"] = `${iapToken}`;
            })
              .as("Cypress-IAP")
              .then(() => {
                return originalFn(subject, ...args);
              });
          });
        } else {
          // If client_id was null, assume there's no IAP and fall back to regular cy.visit
          return originalFn(subject, ...args);
        }
      });
  }
});
```

**Comment by onxrob** [comment]
Thank you for sharing. Unfortunately, we've decided to stop maintaining this project, but hopefully this is helpful for others!
