### ISSUE TITLE
Cypress hangs for me at a specific point when using this plugin for IAP

### ISSUE THREAD

**Issue by nishant-shah-social** [onXmaps/cypress-iap#44]
Hi @coltdorsey ,
Hope you are doing good!
With this new version of IAP published last month I am facing an issue
Cypress would hang for me at a particular point. When I try inspecting my networks tab, I can see there is one XHR which remains in pending state forever when this issue occurs..
I have tried hell lot of options but no luck...I 99% think that the issue is related to IAP hence raising it here..

It used to work fine with the older version of IAP package. It currently works fine against an environment which is not under IAP..
But on executing on an environment under IAP it hangs for me..

I know you must be super busy but will it be possible to get on a call sometime this week and I can share my screen and show?

Thanks,
Nishant Shah

**Comment by coltdorsey** [comment]
@nishant-shah-social Thanks for reaching out. 

Could you include any relevant information in your next reply so we can investigate track and investigate your issue?
