### ISSUE TITLE
Wrong injected header key (should be `Authorization`)

### ISSUE THREAD

**Issue by chiefy** [onXmaps/cypress-iap#45]
Hi, first off, thanks for creating this project, it's exactly what we're trying to get around for testing in our IAP-walled staging environment. 

Anyhow, I had to futz with the code a bit to get it working. I changed the injected header to:
```
req.headers["Authorization"] = `${iapToken}`;
```
and it seemed to get it working. Let me know if you want me to issue a PR

**Comment by coltdorsey** [comment]
Thanks!

As of v2.0, we're using `Proxy-Authorization` header, per google [recommendation](https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_proxy-authorization_header). This solution is still working for us this morning.

Does v2.0 using `Proxy-Authorization` not work for you? If not, what errors are you getting?

**Comment by chiefy** [comment]
Yes, `Proxy-Authorization` was not working. 

So it seems to get a `302` w/ the `Proxy-Authorization` header to a URL like:

```https://accounts.google.com/o/oauth2/v2/auth?client_id=xxx-xxx.apps.googleusercontent.com&response_type=code&scope=openid+email&redirect_uri=https://iap.googleapis.com/v1/oauth/clientIds/xxxx-xxxxx.apps.googleusercontent.com:handleRedirect&code_challenge=a-xxxxxx&code_challenge_method=S256&cred_ref=true&state=xxxxx.xxxxxy9jbG91ZC5nb29nbGUuY29tL2lhcCIsImF1ZCI6IjE0MzMzODg4MjEyNC1nMmJtMm44N2EzcW5sbWZqazkxxxxxWdpbmcucGFyc2xxxxxxmcucGFyc2xleWhlYWx0aC5jb20vIiwiaWF0IjoxNjQ2MzMzNzQ4LCJleHAiOjE2NDYzMzQzNDgsImVuY3J5cHRlZF9jb2RlX3ZlcmlmaWVyIjoiXHUwMDAw4Fx1MDAxZYWZzmJcZlx1MDAwZinPXHUwMDE4TFx1MDAxY1haOVBxxxxxxxxhadJt23tcdTAwMWS_mbDRj6xcdTAwMWG4XHUwMDFld9aiN98ifQ.QTY4vu-xxxxx-87cTw
```

And then the tests just hangs on the standard Google SSO screen waiting for input

**Comment by coltdorsey** [comment]
I'm only able to reproduce this error if I omit the steps outlined in [Google Service Account](https://github.com/onXmaps/cypress-iap#google-service-account).

**Comment by chiefy** [comment]
![Screen Shot 2022-03-04 at 9 01 58 AM](https://user-images.githubusercontent.com/54345/156779845-909f6299-6dc8-40b4-8c9a-488469af4a28.png)

**Comment by coltdorsey** [comment]
Thanks for the screenshot. 

A couple questions / requests:
- What happens if you run this test in run mode (headless)?
- Can you provide a screenshot (like the first) after you replace `Proxy-Authorization` with `Authorization` ?
