### ISSUE TITLE
Performance issue with duplicated intercepts from multiple cy.visit calls in test

### ISSUE THREAD

**Issue by vicwomg** [onXmaps/cypress-iap#50]
Thanks so much for this project, it helped me immensely.

I was noticing some severe performance issues on Github actions leading to failed tests, which were not reproducible on my local machine. Those runners which have limited CPU/memory resources, so that gave me a clue that it could be a leak. 

As it turns out every `cy.visit` call was adding a new intercept alias, and Cypress doesn't simply rewrite the old one. Instead, it duplicates the intercept and subsequently processes each intercept for every request. This causes a memory leak and over time each successive request gets slower and slower and results in timeouts. 

To address this for myself, I added this utility function in my support commands:

```js
export const iapAuthenticate = () => {
  return cy
    .task("getIAPToken", {
      url: Cypress.config().baseUrl,
    })
    .then(iapToken => {
      if (iapToken) {
        return cy
          .log("IAP detected. Adding auth proxy headers to requests.")
          .intercept(`${Cypress.config().baseUrl}/**`, req => {
            req.headers["Proxy-Authorization"] = `${iapToken}`;
          })
          .as("Cypress-IAP");
      } else {
        return cy.log("No IAP detected");
      }
    });
};
```

And call it in the beforeEach of each of my test suites, to explicitly ensure that intercepts are only added once.

Note, I also added the client ID resolver to the plugin file so I wouldn't have to `cy.exec`. Additionally I also persist the iapToken in a plugin variable so it wouldn't duplicate reauthentication:

```js
  // store iapToken for shared use across test run
  var iapToken = null;

  on("task", {
    async getIAPToken({ url }) {
      if (!iapToken && url.indexOf("localhost") == -1) {
        const { exec } = require("child_process");
        const client_id = await new Promise((resolve, reject) => {
          exec(`curl -I ${url} | awk '/^location/ {split($NF, a, /[=&]/); print a[2]}'`, (error, stdout) => {
            if (error) {
              reject(error);
            } else {
              resolve(stdout.trim());
            }
          });
        });
        if (!!client_id) {
          const { GoogleAuth } = require("google-auth-library");
          const auth = new GoogleAuth();
          const client = await auth.getIdTokenClient(client_id.trim());
          const res = await client.request({ url });
          iapToken = res.config.headers.Authorization;
        }
      }
      return iapToken;
    },
  });
```

**Comment by onxrob** [comment]
Thank you for sharing. Unfortunately, we've decided to stop maintaining this project, but hopefully this is helpful for others!
