### ISSUE TITLE
Stopped working, cid is always empty.

### ISSUE THREAD

**Issue by GeorgeXCV** [onXmaps/cypress-iap#57]
I haven't made any changes to my project. When cypress-iap makes a request the `cid` parameter is now always empty. Anyone else having this problem?

<img width="483" alt="Screenshot 2023-09-22 at 15 09 26" src="https://github.com/onXmaps/cypress-iap/assets/13811547/c8ba785a-f4ce-4e09-9eb3-c524f8fa5102">

**Comment by salim-runsafe** [comment]
I just started using this library and ran into this issue, but found that it was because the docker container I was using did not have `curl` installed. `curl` is needed [here](https://github.com/onXmaps/cypress-iap/blob/master/visit.js#L7).
